import { getSession, signOut } from 'next-auth/react';
import Head from 'next/head'
import Layout from '../components/layout/layout'

import styles from '../styles/Home.module.css';

const getAuth = (stringifiedAuth) => {
  //pass session.user.email
  return JSON.parse(stringifiedAuth);
}

export default function Home(props) {
  const { session } = props; 
  const authInfo = getAuth(session.user.email); 

  return (
    <div className={styles.container}>
      <Head>
        <title>K8s Ticketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Layout signOut={signOut} session={session}>
      <div style={{margin: '1rem 0'}}></div>
      <p className={styles.description}>
          {`Welcome to k8s tickets. Your are ${authInfo && authInfo.token? 'Logged in': 'not logged in.'}`}
        </p>
    </Layout>
    </div>
  )
}

export async function getServerSideProps(context){
  const session = await getSession({req: context.req});
  if(!session) {
    return {
      redirect: {
        destination: '/auth',
        permanent: false
      }
    }
  }
  return {
    props: {
      session
    }
  }
}
