import Head from 'next/head'
import Layout from '../components/layout/layout'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>K8s Ticketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Layout>
      <p>Welcome to k8s tickets</p>
    </Layout>
    </div>
  )
}
